#include <../../Game.h>
#include <../../player/Player.h>
#include <../../environment/Map.h>
#include <../../environment/Tile.h>
#include <../../environment/Tilemap.h>
#include <../../unit/Unit.h>
#include <../../unit/UnitManager.h>
#include <../../state/StateManager.h>
#include <../../state/BaseState.h>
#include <../../state/Walking.h>
#include <../../state/Spawning.h>
#include <../../state/Idle.h>
#include <../../state/Despawned.h>
#include <../../state/Harvesting.h>
#include <../../state/Building.h>
#include <../../state/Combat.h>
#include <../../state/Dead.h>
//#include <../../util/Pathfinder.h>
//#include <../../loaders/ResourceLoader.h>