# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Score

import flatbuffers

class ScorePlayer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsScorePlayer(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScorePlayer()
        x.Init(buf, n + offset)
        return x

    # ScorePlayer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScorePlayer
    def PlayerID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ScorePlayer
    def Items(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .ScoreItem import ScoreItem
            obj = ScoreItem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScorePlayer
    def ItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def ScorePlayerStart(builder): builder.StartObject(2)
def ScorePlayerAddPlayerID(builder, playerID): builder.PrependUint32Slot(0, playerID, 0)
def ScorePlayerAddItems(builder, items): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(items), 0)
def ScorePlayerStartItemsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ScorePlayerEnd(builder): return builder.EndObject()
