# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '3.0rc2.dev24+gde873ac.d20230510'
__version_tuple__ = version_tuple = (3, 0, 'dev24', 'gde873ac.d20230510')
